// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  type:       string;
  id:         string;
  geometry:   Geometry;
  properties: Properties;
}

export interface Geometry {
  type:        string;
  coordinates: number[];
}

export interface Properties {
  mapbox_id:       string;
  feature_type:    string;
  name:            string;
  coordinates:     Coordinates;
  place_formatted: string;
  bbox?:           number[];
  context:         Context;
}

export interface Context {
  postcode:      Neighborhood;
  locality?:     Locality;
  place:         Locality;
  region:        Region;
  country:       Country;
  neighborhood?: Neighborhood;
  street?:       Neighborhood;
}

export interface Country {
  mapbox_id:            string;
  name:                 string;
  wikidata_id:          string;
  country_code:         string;
  country_code_alpha_3: string;
}

export interface Locality {
  mapbox_id:    string;
  name:         string;
  wikidata_id?: string;
}

export interface Neighborhood {
  mapbox_id: string;
  name:      string;
}

export interface Region {
  mapbox_id:        string;
  name:             string;
  wikidata_id:      string;
  region_code:      string;
  region_code_full: string;
}

export interface Coordinates {
  longitude: number;
  latitude:  number;
}
